### ISSUE TITLE
Cave Biome Maps does not generate properly

### ISSUE THREAD

**Issue by B-Wither** [min2222/Alex-s-Caves-Backport-Issue-Tracker#1]
As I tested previous 1.19.2 version (1.0.9 port), when I created cave biome map, it just shows "biome.minecraft" and not locate proper biomes. As I tested, even through Nature's Compass can show where these biome is (on Creative), these maps not.
![2024-01-06_12 07 25](https://github.com/min2222/Alex-s-Caves-Backport-Issue-Tracker/assets/63962480/e1160b9e-77a4-4175-9798-611ce3b7af24)

**Comment by min2222** [comment]
fixed
