### ISSUE TITLE
Crash on Japanese language

### ISSUE THREAD

**Issue by B-Wither** [min2222/Alex-s-Caves-Backport-Issue-Tracker#2]
When I tried to see Cave Compendium and Spelunkery Table (when I put Cave Tablet) on Japanese language, it crashes.
[crash-2024-01-02_22.40.48-client.txt](https://github.com/min2222/Alex-s-Caves-Backport-Issue-Tracker/files/13848171/crash-2024-01-02_22.40.48-client.txt)

**Comment by min2222** [comment]
fixed
