### ISSUE TITLE
Crash on Chinese language

### ISSUE THREAD

**Issue by frk920** [min2222/Alex-s-Caves-Backport-Issue-Tracker#4]
I use Alex'sCaves-1.19.2-1
When I use Cave Compendium on Chinese language, it crash
[crash-2024-01-08_13.28.10-client.txt](https://github.com/min2222/Alex-s-Caves-Backport-Issue-Tracker/files/13856657/crash-2024-01-08_13.28.10-client.txt)

**Comment by frk920** [comment]
it said Non [a-z0-9/._-] character in path of location: alexscaves:books/简体中文/root.txt

**Comment by min2222** [comment]
fixed
