### ISSUE TITLE
Can Upload Modpack with Alex Cave Legancy

### ISSUE THREAD

**Issue by SugarDaddii** [min2222/Alex-s-Caves-Backport-Issue-Tracker#7]
Invalid manifest.json file:
References invalid fileIDs: fileID: 5016853, projectID 958645 (Alex's Caves Legacy)

I get this message when i want to upload the file to my modpack
Is there any i can do?

**Comment by min2222** [comment]
it's removed from cf

**Comment by SugarDaddii** [comment]
Will it come back?

**Comment by min2222** [comment]
no

**Comment by SugarDaddii** [comment]
Are in trouble now fk? I thought this is great someone put the effort in backporting … and now putting down I feel you sry
